-- Create Contacts Table
CREATE TABLE contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  type TEXT,
  tag TEXT,
  status TEXT DEFAULT 'new',
  last_visit TEXT DEFAULT 'Today',
  visits_count INT DEFAULT 0,
  avatar TEXT,
  color TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create Campaigns Table
CREATE TABLE campaigns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT,
  icon TEXT,
  color TEXT,
  status TEXT DEFAULT 'live',
  sent_count INT DEFAULT 0,
  opened_count INT DEFAULT 0,
  replied_count INT DEFAULT 0,
  trigger_date TEXT,
  template TEXT,
  segment TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create AI Config Table
CREATE TABLE ai_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_context TEXT,
  tone TEXT DEFAULT 'Friendly',
  business_hours TEXT,
  enabled BOOLEAN DEFAULT true,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert Default AI Config so it always exists
INSERT INTO ai_config (id, business_context, tone, business_hours) 
VALUES (1, 'We are a local business.', 'Friendly', 'Mon-Sat 10AM-8PM');
